package com.xiangshangkan.framtest.auto.dao;

import com.xiangshangkan.framtest.auto.entity.CertificateKeepLogEntity;
import com.xiangshangkan.framtest.auto.entity.CertificateKeepLogEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CertificateKeepLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int countByExample(CertificateKeepLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int deleteByExample(CertificateKeepLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int insert(CertificateKeepLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int insertSelective(CertificateKeepLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    List<CertificateKeepLogEntity> selectByExampleWithRowbounds(CertificateKeepLogEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    List<CertificateKeepLogEntity> selectByExample(CertificateKeepLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    CertificateKeepLogEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CertificateKeepLogEntity record, @Param("example") CertificateKeepLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CertificateKeepLogEntity record, @Param("example") CertificateKeepLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CertificateKeepLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_keep_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CertificateKeepLogEntity record);
}