package com.xiangshangkan.framtest.auto.dao;

import com.xiangshangkan.framtest.auto.entity.CertificateInfoEntity;
import com.xiangshangkan.framtest.auto.entity.CertificateInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CertificateInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int countByExample(CertificateInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int deleteByExample(CertificateInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int insert(CertificateInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int insertSelective(CertificateInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    List<CertificateInfoEntity> selectByExampleWithRowbounds(CertificateInfoEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    List<CertificateInfoEntity> selectByExample(CertificateInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    CertificateInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CertificateInfoEntity record, @Param("example") CertificateInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CertificateInfoEntity record, @Param("example") CertificateInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CertificateInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CertificateInfoEntity record);
}