package com.xiangshangkan.framtest.auto.dao;

import com.xiangshangkan.framtest.auto.entity.CmDictionaryEntity;
import com.xiangshangkan.framtest.auto.entity.CmDictionaryEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CmDictionaryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    int countByExample(CmDictionaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    int deleteByExample(CmDictionaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    int insert(CmDictionaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(CmDictionaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    List<CmDictionaryEntity> selectByExampleWithRowbounds(CmDictionaryEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    List<CmDictionaryEntity> selectByExample(CmDictionaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CmDictionaryEntity record, @Param("example") CmDictionaryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CmDictionaryEntity record, @Param("example") CmDictionaryEntityExample example);
}