package com.xiangshangkan.framtest.auto.dao;

import com.xiangshangkan.framtest.auto.entity.LicenseBusinessInfoEntity;
import com.xiangshangkan.framtest.auto.entity.LicenseBusinessInfoEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LicenseBusinessInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int countByExample(LicenseBusinessInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int deleteByExample(LicenseBusinessInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int insert(LicenseBusinessInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int insertSelective(LicenseBusinessInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    List<LicenseBusinessInfoEntity> selectByExampleWithRowbounds(LicenseBusinessInfoEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    List<LicenseBusinessInfoEntity> selectByExample(LicenseBusinessInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    LicenseBusinessInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LicenseBusinessInfoEntity record, @Param("example") LicenseBusinessInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LicenseBusinessInfoEntity record, @Param("example") LicenseBusinessInfoEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LicenseBusinessInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LicenseBusinessInfoEntity record);
}