package com.xiangshangkan.framtest.auto.entity.study;

import java.io.Serializable;
import java.util.Date;

public class NhrQualificationEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.worker_id
     *
     * @mbggenerated
     */
    private String workerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.issu_time
     *
     * @mbggenerated
     */
    private Date issuTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.continuing_education_time
     *
     * @mbggenerated
     */
    private Date continuingEducationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.insert_time
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.BI_DATE
     *
     * @mbggenerated
     */
    private Date biDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nhr_qualification.city_id
     *
     * @mbggenerated
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nhr_qualification
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.id
     *
     * @return the value of nhr_qualification.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.id
     *
     * @param id the value for nhr_qualification.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.type
     *
     * @return the value of nhr_qualification.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.type
     *
     * @param type the value for nhr_qualification.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.worker_id
     *
     * @return the value of nhr_qualification.worker_id
     *
     * @mbggenerated
     */
    public String getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.worker_id
     *
     * @param workerId the value for nhr_qualification.worker_id
     *
     * @mbggenerated
     */
    public void setWorkerId(String workerId) {
        this.workerId = workerId == null ? null : workerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.name
     *
     * @return the value of nhr_qualification.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.name
     *
     * @param name the value for nhr_qualification.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.number
     *
     * @return the value of nhr_qualification.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.number
     *
     * @param number the value for nhr_qualification.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.issu_time
     *
     * @return the value of nhr_qualification.issu_time
     *
     * @mbggenerated
     */
    public Date getIssuTime() {
        return issuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.issu_time
     *
     * @param issuTime the value for nhr_qualification.issu_time
     *
     * @mbggenerated
     */
    public void setIssuTime(Date issuTime) {
        this.issuTime = issuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.begin_time
     *
     * @return the value of nhr_qualification.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.begin_time
     *
     * @param beginTime the value for nhr_qualification.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.end_time
     *
     * @return the value of nhr_qualification.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.end_time
     *
     * @param endTime the value for nhr_qualification.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.continuing_education_time
     *
     * @return the value of nhr_qualification.continuing_education_time
     *
     * @mbggenerated
     */
    public Date getContinuingEducationTime() {
        return continuingEducationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.continuing_education_time
     *
     * @param continuingEducationTime the value for nhr_qualification.continuing_education_time
     *
     * @mbggenerated
     */
    public void setContinuingEducationTime(Date continuingEducationTime) {
        this.continuingEducationTime = continuingEducationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.insert_time
     *
     * @return the value of nhr_qualification.insert_time
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.insert_time
     *
     * @param insertTime the value for nhr_qualification.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.BI_DATE
     *
     * @return the value of nhr_qualification.BI_DATE
     *
     * @mbggenerated
     */
    public Date getBiDate() {
        return biDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.BI_DATE
     *
     * @param biDate the value for nhr_qualification.BI_DATE
     *
     * @mbggenerated
     */
    public void setBiDate(Date biDate) {
        this.biDate = biDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nhr_qualification.city_id
     *
     * @return the value of nhr_qualification.city_id
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nhr_qualification.city_id
     *
     * @param cityId the value for nhr_qualification.city_id
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhr_qualification
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", workerId=").append(workerId);
        sb.append(", name=").append(name);
        sb.append(", number=").append(number);
        sb.append(", issuTime=").append(issuTime);
        sb.append(", beginTime=").append(beginTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", continuingEducationTime=").append(continuingEducationTime);
        sb.append(", insertTime=").append(insertTime);
        sb.append(", biDate=").append(biDate);
        sb.append(", cityId=").append(cityId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhr_qualification
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NhrQualificationEntity other = (NhrQualificationEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getWorkerId() == null ? other.getWorkerId() == null : this.getWorkerId().equals(other.getWorkerId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
            && (this.getIssuTime() == null ? other.getIssuTime() == null : this.getIssuTime().equals(other.getIssuTime()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getContinuingEducationTime() == null ? other.getContinuingEducationTime() == null : this.getContinuingEducationTime().equals(other.getContinuingEducationTime()))
            && (this.getInsertTime() == null ? other.getInsertTime() == null : this.getInsertTime().equals(other.getInsertTime()))
            && (this.getBiDate() == null ? other.getBiDate() == null : this.getBiDate().equals(other.getBiDate()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nhr_qualification
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getWorkerId() == null) ? 0 : getWorkerId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getIssuTime() == null) ? 0 : getIssuTime().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getContinuingEducationTime() == null) ? 0 : getContinuingEducationTime().hashCode());
        result = prime * result + ((getInsertTime() == null) ? 0 : getInsertTime().hashCode());
        result = prime * result + ((getBiDate() == null) ? 0 : getBiDate().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        return result;
    }
}