package com.xiangshangkan.framtest.auto.entity;

import java.io.Serializable;
import java.util.Date;

public class CertificateInfoEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.person_name
     *
     * @mbggenerated
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.person_number
     *
     * @mbggenerated
     */
    private String personNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.person_dept
     *
     * @mbggenerated
     */
    private String personDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.person_dept_number
     *
     * @mbggenerated
     */
    private String personDeptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.person_status
     *
     * @mbggenerated
     */
    private String personStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.management_number
     *
     * @mbggenerated
     */
    private String managementNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.certificate_number
     *
     * @mbggenerated
     */
    private String certificateNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.register_number
     *
     * @mbggenerated
     */
    private String registerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.continuing_education_time
     *
     * @mbggenerated
     */
    private Date continuingEducationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.custodian
     *
     * @mbggenerated
     */
    private String custodian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.custodian_number
     *
     * @mbggenerated
     */
    private String custodianNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.custodian_dept
     *
     * @mbggenerated
     */
    private String custodianDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.cusotidan_dept_number
     *
     * @mbggenerated
     */
    private String cusotidanDeptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.institute
     *
     * @mbggenerated
     */
    private String institute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.institute_old_id
     *
     * @mbggenerated
     */
    private String instituteOldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.store_serial
     *
     * @mbggenerated
     */
    private String storeSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_start_time
     *
     * @mbggenerated
     */
    private Date keyStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_end_time
     *
     * @mbggenerated
     */
    private Date keyEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_authority
     *
     * @mbggenerated
     */
    private Integer keyAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_login_account
     *
     * @mbggenerated
     */
    private String keyLoginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_login_pw
     *
     * @mbggenerated
     */
    private String keyLoginPw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_custodian
     *
     * @mbggenerated
     */
    private String keyCustodian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_custodian_number
     *
     * @mbggenerated
     */
    private String keyCustodianNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_custodian_dept
     *
     * @mbggenerated
     */
    private String keyCustodianDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.key_custodian_dept_number
     *
     * @mbggenerated
     */
    private String keyCustodianDeptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.expire_time
     *
     * @mbggenerated
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.start_keep_time
     *
     * @mbggenerated
     */
    private Date startKeepTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.end_keep_time
     *
     * @mbggenerated
     */
    private Date endKeepTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.start_use_time
     *
     * @mbggenerated
     */
    private Date startUseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.end_use_time
     *
     * @mbggenerated
     */
    private Date endUseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.registration_date
     *
     * @mbggenerated
     */
    private Date registrationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.bankcardname
     *
     * @mbggenerated
     */
    private String bankcardname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.provinceId
     *
     * @mbggenerated
     */
    private String provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.cityId
     *
     * @mbggenerated
     */
    private String cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.openbank
     *
     * @mbggenerated
     */
    private String openbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.bankcard
     *
     * @mbggenerated
     */
    private String bankcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificate_info.rentprice
     *
     * @mbggenerated
     */
    private String rentprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.id
     *
     * @return the value of certificate_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.id
     *
     * @param id the value for certificate_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.type
     *
     * @return the value of certificate_info.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.type
     *
     * @param type the value for certificate_info.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.source
     *
     * @return the value of certificate_info.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.source
     *
     * @param source the value for certificate_info.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.person_name
     *
     * @return the value of certificate_info.person_name
     *
     * @mbggenerated
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.person_name
     *
     * @param personName the value for certificate_info.person_name
     *
     * @mbggenerated
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.person_number
     *
     * @return the value of certificate_info.person_number
     *
     * @mbggenerated
     */
    public String getPersonNumber() {
        return personNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.person_number
     *
     * @param personNumber the value for certificate_info.person_number
     *
     * @mbggenerated
     */
    public void setPersonNumber(String personNumber) {
        this.personNumber = personNumber == null ? null : personNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.person_dept
     *
     * @return the value of certificate_info.person_dept
     *
     * @mbggenerated
     */
    public String getPersonDept() {
        return personDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.person_dept
     *
     * @param personDept the value for certificate_info.person_dept
     *
     * @mbggenerated
     */
    public void setPersonDept(String personDept) {
        this.personDept = personDept == null ? null : personDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.person_dept_number
     *
     * @return the value of certificate_info.person_dept_number
     *
     * @mbggenerated
     */
    public String getPersonDeptNumber() {
        return personDeptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.person_dept_number
     *
     * @param personDeptNumber the value for certificate_info.person_dept_number
     *
     * @mbggenerated
     */
    public void setPersonDeptNumber(String personDeptNumber) {
        this.personDeptNumber = personDeptNumber == null ? null : personDeptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.person_status
     *
     * @return the value of certificate_info.person_status
     *
     * @mbggenerated
     */
    public String getPersonStatus() {
        return personStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.person_status
     *
     * @param personStatus the value for certificate_info.person_status
     *
     * @mbggenerated
     */
    public void setPersonStatus(String personStatus) {
        this.personStatus = personStatus == null ? null : personStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.id_card
     *
     * @return the value of certificate_info.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.id_card
     *
     * @param idCard the value for certificate_info.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.management_number
     *
     * @return the value of certificate_info.management_number
     *
     * @mbggenerated
     */
    public String getManagementNumber() {
        return managementNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.management_number
     *
     * @param managementNumber the value for certificate_info.management_number
     *
     * @mbggenerated
     */
    public void setManagementNumber(String managementNumber) {
        this.managementNumber = managementNumber == null ? null : managementNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.certificate_number
     *
     * @return the value of certificate_info.certificate_number
     *
     * @mbggenerated
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.certificate_number
     *
     * @param certificateNumber the value for certificate_info.certificate_number
     *
     * @mbggenerated
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber == null ? null : certificateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.register_number
     *
     * @return the value of certificate_info.register_number
     *
     * @mbggenerated
     */
    public String getRegisterNumber() {
        return registerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.register_number
     *
     * @param registerNumber the value for certificate_info.register_number
     *
     * @mbggenerated
     */
    public void setRegisterNumber(String registerNumber) {
        this.registerNumber = registerNumber == null ? null : registerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.continuing_education_time
     *
     * @return the value of certificate_info.continuing_education_time
     *
     * @mbggenerated
     */
    public Date getContinuingEducationTime() {
        return continuingEducationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.continuing_education_time
     *
     * @param continuingEducationTime the value for certificate_info.continuing_education_time
     *
     * @mbggenerated
     */
    public void setContinuingEducationTime(Date continuingEducationTime) {
        this.continuingEducationTime = continuingEducationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.custodian
     *
     * @return the value of certificate_info.custodian
     *
     * @mbggenerated
     */
    public String getCustodian() {
        return custodian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.custodian
     *
     * @param custodian the value for certificate_info.custodian
     *
     * @mbggenerated
     */
    public void setCustodian(String custodian) {
        this.custodian = custodian == null ? null : custodian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.custodian_number
     *
     * @return the value of certificate_info.custodian_number
     *
     * @mbggenerated
     */
    public String getCustodianNumber() {
        return custodianNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.custodian_number
     *
     * @param custodianNumber the value for certificate_info.custodian_number
     *
     * @mbggenerated
     */
    public void setCustodianNumber(String custodianNumber) {
        this.custodianNumber = custodianNumber == null ? null : custodianNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.custodian_dept
     *
     * @return the value of certificate_info.custodian_dept
     *
     * @mbggenerated
     */
    public String getCustodianDept() {
        return custodianDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.custodian_dept
     *
     * @param custodianDept the value for certificate_info.custodian_dept
     *
     * @mbggenerated
     */
    public void setCustodianDept(String custodianDept) {
        this.custodianDept = custodianDept == null ? null : custodianDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.cusotidan_dept_number
     *
     * @return the value of certificate_info.cusotidan_dept_number
     *
     * @mbggenerated
     */
    public String getCusotidanDeptNumber() {
        return cusotidanDeptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.cusotidan_dept_number
     *
     * @param cusotidanDeptNumber the value for certificate_info.cusotidan_dept_number
     *
     * @mbggenerated
     */
    public void setCusotidanDeptNumber(String cusotidanDeptNumber) {
        this.cusotidanDeptNumber = cusotidanDeptNumber == null ? null : cusotidanDeptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.institute
     *
     * @return the value of certificate_info.institute
     *
     * @mbggenerated
     */
    public String getInstitute() {
        return institute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.institute
     *
     * @param institute the value for certificate_info.institute
     *
     * @mbggenerated
     */
    public void setInstitute(String institute) {
        this.institute = institute == null ? null : institute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.institute_old_id
     *
     * @return the value of certificate_info.institute_old_id
     *
     * @mbggenerated
     */
    public String getInstituteOldId() {
        return instituteOldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.institute_old_id
     *
     * @param instituteOldId the value for certificate_info.institute_old_id
     *
     * @mbggenerated
     */
    public void setInstituteOldId(String instituteOldId) {
        this.instituteOldId = instituteOldId == null ? null : instituteOldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.store_serial
     *
     * @return the value of certificate_info.store_serial
     *
     * @mbggenerated
     */
    public String getStoreSerial() {
        return storeSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.store_serial
     *
     * @param storeSerial the value for certificate_info.store_serial
     *
     * @mbggenerated
     */
    public void setStoreSerial(String storeSerial) {
        this.storeSerial = storeSerial == null ? null : storeSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_start_time
     *
     * @return the value of certificate_info.key_start_time
     *
     * @mbggenerated
     */
    public Date getKeyStartTime() {
        return keyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_start_time
     *
     * @param keyStartTime the value for certificate_info.key_start_time
     *
     * @mbggenerated
     */
    public void setKeyStartTime(Date keyStartTime) {
        this.keyStartTime = keyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_end_time
     *
     * @return the value of certificate_info.key_end_time
     *
     * @mbggenerated
     */
    public Date getKeyEndTime() {
        return keyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_end_time
     *
     * @param keyEndTime the value for certificate_info.key_end_time
     *
     * @mbggenerated
     */
    public void setKeyEndTime(Date keyEndTime) {
        this.keyEndTime = keyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_authority
     *
     * @return the value of certificate_info.key_authority
     *
     * @mbggenerated
     */
    public Integer getKeyAuthority() {
        return keyAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_authority
     *
     * @param keyAuthority the value for certificate_info.key_authority
     *
     * @mbggenerated
     */
    public void setKeyAuthority(Integer keyAuthority) {
        this.keyAuthority = keyAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_login_account
     *
     * @return the value of certificate_info.key_login_account
     *
     * @mbggenerated
     */
    public String getKeyLoginAccount() {
        return keyLoginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_login_account
     *
     * @param keyLoginAccount the value for certificate_info.key_login_account
     *
     * @mbggenerated
     */
    public void setKeyLoginAccount(String keyLoginAccount) {
        this.keyLoginAccount = keyLoginAccount == null ? null : keyLoginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_login_pw
     *
     * @return the value of certificate_info.key_login_pw
     *
     * @mbggenerated
     */
    public String getKeyLoginPw() {
        return keyLoginPw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_login_pw
     *
     * @param keyLoginPw the value for certificate_info.key_login_pw
     *
     * @mbggenerated
     */
    public void setKeyLoginPw(String keyLoginPw) {
        this.keyLoginPw = keyLoginPw == null ? null : keyLoginPw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_custodian
     *
     * @return the value of certificate_info.key_custodian
     *
     * @mbggenerated
     */
    public String getKeyCustodian() {
        return keyCustodian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_custodian
     *
     * @param keyCustodian the value for certificate_info.key_custodian
     *
     * @mbggenerated
     */
    public void setKeyCustodian(String keyCustodian) {
        this.keyCustodian = keyCustodian == null ? null : keyCustodian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_custodian_number
     *
     * @return the value of certificate_info.key_custodian_number
     *
     * @mbggenerated
     */
    public String getKeyCustodianNumber() {
        return keyCustodianNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_custodian_number
     *
     * @param keyCustodianNumber the value for certificate_info.key_custodian_number
     *
     * @mbggenerated
     */
    public void setKeyCustodianNumber(String keyCustodianNumber) {
        this.keyCustodianNumber = keyCustodianNumber == null ? null : keyCustodianNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_custodian_dept
     *
     * @return the value of certificate_info.key_custodian_dept
     *
     * @mbggenerated
     */
    public String getKeyCustodianDept() {
        return keyCustodianDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_custodian_dept
     *
     * @param keyCustodianDept the value for certificate_info.key_custodian_dept
     *
     * @mbggenerated
     */
    public void setKeyCustodianDept(String keyCustodianDept) {
        this.keyCustodianDept = keyCustodianDept == null ? null : keyCustodianDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.key_custodian_dept_number
     *
     * @return the value of certificate_info.key_custodian_dept_number
     *
     * @mbggenerated
     */
    public String getKeyCustodianDeptNumber() {
        return keyCustodianDeptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.key_custodian_dept_number
     *
     * @param keyCustodianDeptNumber the value for certificate_info.key_custodian_dept_number
     *
     * @mbggenerated
     */
    public void setKeyCustodianDeptNumber(String keyCustodianDeptNumber) {
        this.keyCustodianDeptNumber = keyCustodianDeptNumber == null ? null : keyCustodianDeptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.status
     *
     * @return the value of certificate_info.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.status
     *
     * @param status the value for certificate_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.expire_time
     *
     * @return the value of certificate_info.expire_time
     *
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.expire_time
     *
     * @param expireTime the value for certificate_info.expire_time
     *
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.start_keep_time
     *
     * @return the value of certificate_info.start_keep_time
     *
     * @mbggenerated
     */
    public Date getStartKeepTime() {
        return startKeepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.start_keep_time
     *
     * @param startKeepTime the value for certificate_info.start_keep_time
     *
     * @mbggenerated
     */
    public void setStartKeepTime(Date startKeepTime) {
        this.startKeepTime = startKeepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.end_keep_time
     *
     * @return the value of certificate_info.end_keep_time
     *
     * @mbggenerated
     */
    public Date getEndKeepTime() {
        return endKeepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.end_keep_time
     *
     * @param endKeepTime the value for certificate_info.end_keep_time
     *
     * @mbggenerated
     */
    public void setEndKeepTime(Date endKeepTime) {
        this.endKeepTime = endKeepTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.start_use_time
     *
     * @return the value of certificate_info.start_use_time
     *
     * @mbggenerated
     */
    public Date getStartUseTime() {
        return startUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.start_use_time
     *
     * @param startUseTime the value for certificate_info.start_use_time
     *
     * @mbggenerated
     */
    public void setStartUseTime(Date startUseTime) {
        this.startUseTime = startUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.end_use_time
     *
     * @return the value of certificate_info.end_use_time
     *
     * @mbggenerated
     */
    public Date getEndUseTime() {
        return endUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.end_use_time
     *
     * @param endUseTime the value for certificate_info.end_use_time
     *
     * @mbggenerated
     */
    public void setEndUseTime(Date endUseTime) {
        this.endUseTime = endUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.create_time
     *
     * @return the value of certificate_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.create_time
     *
     * @param createTime the value for certificate_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.update_time
     *
     * @return the value of certificate_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.update_time
     *
     * @param updateTime the value for certificate_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.registration_date
     *
     * @return the value of certificate_info.registration_date
     *
     * @mbggenerated
     */
    public Date getRegistrationDate() {
        return registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.registration_date
     *
     * @param registrationDate the value for certificate_info.registration_date
     *
     * @mbggenerated
     */
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.bankcardname
     *
     * @return the value of certificate_info.bankcardname
     *
     * @mbggenerated
     */
    public String getBankcardname() {
        return bankcardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.bankcardname
     *
     * @param bankcardname the value for certificate_info.bankcardname
     *
     * @mbggenerated
     */
    public void setBankcardname(String bankcardname) {
        this.bankcardname = bankcardname == null ? null : bankcardname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.provinceId
     *
     * @return the value of certificate_info.provinceId
     *
     * @mbggenerated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.provinceId
     *
     * @param provinceid the value for certificate_info.provinceId
     *
     * @mbggenerated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.cityId
     *
     * @return the value of certificate_info.cityId
     *
     * @mbggenerated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.cityId
     *
     * @param cityid the value for certificate_info.cityId
     *
     * @mbggenerated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.openbank
     *
     * @return the value of certificate_info.openbank
     *
     * @mbggenerated
     */
    public String getOpenbank() {
        return openbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.openbank
     *
     * @param openbank the value for certificate_info.openbank
     *
     * @mbggenerated
     */
    public void setOpenbank(String openbank) {
        this.openbank = openbank == null ? null : openbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.bankcard
     *
     * @return the value of certificate_info.bankcard
     *
     * @mbggenerated
     */
    public String getBankcard() {
        return bankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.bankcard
     *
     * @param bankcard the value for certificate_info.bankcard
     *
     * @mbggenerated
     */
    public void setBankcard(String bankcard) {
        this.bankcard = bankcard == null ? null : bankcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificate_info.rentprice
     *
     * @return the value of certificate_info.rentprice
     *
     * @mbggenerated
     */
    public String getRentprice() {
        return rentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificate_info.rentprice
     *
     * @param rentprice the value for certificate_info.rentprice
     *
     * @mbggenerated
     */
    public void setRentprice(String rentprice) {
        this.rentprice = rentprice == null ? null : rentprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", type=").append(type);
        sb.append(", source=").append(source);
        sb.append(", personName=").append(personName);
        sb.append(", personNumber=").append(personNumber);
        sb.append(", personDept=").append(personDept);
        sb.append(", personDeptNumber=").append(personDeptNumber);
        sb.append(", personStatus=").append(personStatus);
        sb.append(", idCard=").append(idCard);
        sb.append(", managementNumber=").append(managementNumber);
        sb.append(", certificateNumber=").append(certificateNumber);
        sb.append(", registerNumber=").append(registerNumber);
        sb.append(", continuingEducationTime=").append(continuingEducationTime);
        sb.append(", custodian=").append(custodian);
        sb.append(", custodianNumber=").append(custodianNumber);
        sb.append(", custodianDept=").append(custodianDept);
        sb.append(", cusotidanDeptNumber=").append(cusotidanDeptNumber);
        sb.append(", institute=").append(institute);
        sb.append(", instituteOldId=").append(instituteOldId);
        sb.append(", storeSerial=").append(storeSerial);
        sb.append(", keyStartTime=").append(keyStartTime);
        sb.append(", keyEndTime=").append(keyEndTime);
        sb.append(", keyAuthority=").append(keyAuthority);
        sb.append(", keyLoginAccount=").append(keyLoginAccount);
        sb.append(", keyLoginPw=").append(keyLoginPw);
        sb.append(", keyCustodian=").append(keyCustodian);
        sb.append(", keyCustodianNumber=").append(keyCustodianNumber);
        sb.append(", keyCustodianDept=").append(keyCustodianDept);
        sb.append(", keyCustodianDeptNumber=").append(keyCustodianDeptNumber);
        sb.append(", status=").append(status);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", startKeepTime=").append(startKeepTime);
        sb.append(", endKeepTime=").append(endKeepTime);
        sb.append(", startUseTime=").append(startUseTime);
        sb.append(", endUseTime=").append(endUseTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", registrationDate=").append(registrationDate);
        sb.append(", bankcardname=").append(bankcardname);
        sb.append(", provinceid=").append(provinceid);
        sb.append(", cityid=").append(cityid);
        sb.append(", openbank=").append(openbank);
        sb.append(", bankcard=").append(bankcard);
        sb.append(", rentprice=").append(rentprice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CertificateInfoEntity other = (CertificateInfoEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getPersonName() == null ? other.getPersonName() == null : this.getPersonName().equals(other.getPersonName()))
            && (this.getPersonNumber() == null ? other.getPersonNumber() == null : this.getPersonNumber().equals(other.getPersonNumber()))
            && (this.getPersonDept() == null ? other.getPersonDept() == null : this.getPersonDept().equals(other.getPersonDept()))
            && (this.getPersonDeptNumber() == null ? other.getPersonDeptNumber() == null : this.getPersonDeptNumber().equals(other.getPersonDeptNumber()))
            && (this.getPersonStatus() == null ? other.getPersonStatus() == null : this.getPersonStatus().equals(other.getPersonStatus()))
            && (this.getIdCard() == null ? other.getIdCard() == null : this.getIdCard().equals(other.getIdCard()))
            && (this.getManagementNumber() == null ? other.getManagementNumber() == null : this.getManagementNumber().equals(other.getManagementNumber()))
            && (this.getCertificateNumber() == null ? other.getCertificateNumber() == null : this.getCertificateNumber().equals(other.getCertificateNumber()))
            && (this.getRegisterNumber() == null ? other.getRegisterNumber() == null : this.getRegisterNumber().equals(other.getRegisterNumber()))
            && (this.getContinuingEducationTime() == null ? other.getContinuingEducationTime() == null : this.getContinuingEducationTime().equals(other.getContinuingEducationTime()))
            && (this.getCustodian() == null ? other.getCustodian() == null : this.getCustodian().equals(other.getCustodian()))
            && (this.getCustodianNumber() == null ? other.getCustodianNumber() == null : this.getCustodianNumber().equals(other.getCustodianNumber()))
            && (this.getCustodianDept() == null ? other.getCustodianDept() == null : this.getCustodianDept().equals(other.getCustodianDept()))
            && (this.getCusotidanDeptNumber() == null ? other.getCusotidanDeptNumber() == null : this.getCusotidanDeptNumber().equals(other.getCusotidanDeptNumber()))
            && (this.getInstitute() == null ? other.getInstitute() == null : this.getInstitute().equals(other.getInstitute()))
            && (this.getInstituteOldId() == null ? other.getInstituteOldId() == null : this.getInstituteOldId().equals(other.getInstituteOldId()))
            && (this.getStoreSerial() == null ? other.getStoreSerial() == null : this.getStoreSerial().equals(other.getStoreSerial()))
            && (this.getKeyStartTime() == null ? other.getKeyStartTime() == null : this.getKeyStartTime().equals(other.getKeyStartTime()))
            && (this.getKeyEndTime() == null ? other.getKeyEndTime() == null : this.getKeyEndTime().equals(other.getKeyEndTime()))
            && (this.getKeyAuthority() == null ? other.getKeyAuthority() == null : this.getKeyAuthority().equals(other.getKeyAuthority()))
            && (this.getKeyLoginAccount() == null ? other.getKeyLoginAccount() == null : this.getKeyLoginAccount().equals(other.getKeyLoginAccount()))
            && (this.getKeyLoginPw() == null ? other.getKeyLoginPw() == null : this.getKeyLoginPw().equals(other.getKeyLoginPw()))
            && (this.getKeyCustodian() == null ? other.getKeyCustodian() == null : this.getKeyCustodian().equals(other.getKeyCustodian()))
            && (this.getKeyCustodianNumber() == null ? other.getKeyCustodianNumber() == null : this.getKeyCustodianNumber().equals(other.getKeyCustodianNumber()))
            && (this.getKeyCustodianDept() == null ? other.getKeyCustodianDept() == null : this.getKeyCustodianDept().equals(other.getKeyCustodianDept()))
            && (this.getKeyCustodianDeptNumber() == null ? other.getKeyCustodianDeptNumber() == null : this.getKeyCustodianDeptNumber().equals(other.getKeyCustodianDeptNumber()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getExpireTime() == null ? other.getExpireTime() == null : this.getExpireTime().equals(other.getExpireTime()))
            && (this.getStartKeepTime() == null ? other.getStartKeepTime() == null : this.getStartKeepTime().equals(other.getStartKeepTime()))
            && (this.getEndKeepTime() == null ? other.getEndKeepTime() == null : this.getEndKeepTime().equals(other.getEndKeepTime()))
            && (this.getStartUseTime() == null ? other.getStartUseTime() == null : this.getStartUseTime().equals(other.getStartUseTime()))
            && (this.getEndUseTime() == null ? other.getEndUseTime() == null : this.getEndUseTime().equals(other.getEndUseTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getRegistrationDate() == null ? other.getRegistrationDate() == null : this.getRegistrationDate().equals(other.getRegistrationDate()))
            && (this.getBankcardname() == null ? other.getBankcardname() == null : this.getBankcardname().equals(other.getBankcardname()))
            && (this.getProvinceid() == null ? other.getProvinceid() == null : this.getProvinceid().equals(other.getProvinceid()))
            && (this.getCityid() == null ? other.getCityid() == null : this.getCityid().equals(other.getCityid()))
            && (this.getOpenbank() == null ? other.getOpenbank() == null : this.getOpenbank().equals(other.getOpenbank()))
            && (this.getBankcard() == null ? other.getBankcard() == null : this.getBankcard().equals(other.getBankcard()))
            && (this.getRentprice() == null ? other.getRentprice() == null : this.getRentprice().equals(other.getRentprice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificate_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getPersonName() == null) ? 0 : getPersonName().hashCode());
        result = prime * result + ((getPersonNumber() == null) ? 0 : getPersonNumber().hashCode());
        result = prime * result + ((getPersonDept() == null) ? 0 : getPersonDept().hashCode());
        result = prime * result + ((getPersonDeptNumber() == null) ? 0 : getPersonDeptNumber().hashCode());
        result = prime * result + ((getPersonStatus() == null) ? 0 : getPersonStatus().hashCode());
        result = prime * result + ((getIdCard() == null) ? 0 : getIdCard().hashCode());
        result = prime * result + ((getManagementNumber() == null) ? 0 : getManagementNumber().hashCode());
        result = prime * result + ((getCertificateNumber() == null) ? 0 : getCertificateNumber().hashCode());
        result = prime * result + ((getRegisterNumber() == null) ? 0 : getRegisterNumber().hashCode());
        result = prime * result + ((getContinuingEducationTime() == null) ? 0 : getContinuingEducationTime().hashCode());
        result = prime * result + ((getCustodian() == null) ? 0 : getCustodian().hashCode());
        result = prime * result + ((getCustodianNumber() == null) ? 0 : getCustodianNumber().hashCode());
        result = prime * result + ((getCustodianDept() == null) ? 0 : getCustodianDept().hashCode());
        result = prime * result + ((getCusotidanDeptNumber() == null) ? 0 : getCusotidanDeptNumber().hashCode());
        result = prime * result + ((getInstitute() == null) ? 0 : getInstitute().hashCode());
        result = prime * result + ((getInstituteOldId() == null) ? 0 : getInstituteOldId().hashCode());
        result = prime * result + ((getStoreSerial() == null) ? 0 : getStoreSerial().hashCode());
        result = prime * result + ((getKeyStartTime() == null) ? 0 : getKeyStartTime().hashCode());
        result = prime * result + ((getKeyEndTime() == null) ? 0 : getKeyEndTime().hashCode());
        result = prime * result + ((getKeyAuthority() == null) ? 0 : getKeyAuthority().hashCode());
        result = prime * result + ((getKeyLoginAccount() == null) ? 0 : getKeyLoginAccount().hashCode());
        result = prime * result + ((getKeyLoginPw() == null) ? 0 : getKeyLoginPw().hashCode());
        result = prime * result + ((getKeyCustodian() == null) ? 0 : getKeyCustodian().hashCode());
        result = prime * result + ((getKeyCustodianNumber() == null) ? 0 : getKeyCustodianNumber().hashCode());
        result = prime * result + ((getKeyCustodianDept() == null) ? 0 : getKeyCustodianDept().hashCode());
        result = prime * result + ((getKeyCustodianDeptNumber() == null) ? 0 : getKeyCustodianDeptNumber().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getExpireTime() == null) ? 0 : getExpireTime().hashCode());
        result = prime * result + ((getStartKeepTime() == null) ? 0 : getStartKeepTime().hashCode());
        result = prime * result + ((getEndKeepTime() == null) ? 0 : getEndKeepTime().hashCode());
        result = prime * result + ((getStartUseTime() == null) ? 0 : getStartUseTime().hashCode());
        result = prime * result + ((getEndUseTime() == null) ? 0 : getEndUseTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getRegistrationDate() == null) ? 0 : getRegistrationDate().hashCode());
        result = prime * result + ((getBankcardname() == null) ? 0 : getBankcardname().hashCode());
        result = prime * result + ((getProvinceid() == null) ? 0 : getProvinceid().hashCode());
        result = prime * result + ((getCityid() == null) ? 0 : getCityid().hashCode());
        result = prime * result + ((getOpenbank() == null) ? 0 : getOpenbank().hashCode());
        result = prime * result + ((getBankcard() == null) ? 0 : getBankcard().hashCode());
        result = prime * result + ((getRentprice() == null) ? 0 : getRentprice().hashCode());
        return result;
    }
}