package com.xiangshangkan.framtest.auto.entity;

import java.util.ArrayList;
import java.util.List;

public class CmDictionaryEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public CmDictionaryEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDicidIsNull() {
            addCriterion("DicID is null");
            return (Criteria) this;
        }

        public Criteria andDicidIsNotNull() {
            addCriterion("DicID is not null");
            return (Criteria) this;
        }

        public Criteria andDicidEqualTo(String value) {
            addCriterion("DicID =", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidNotEqualTo(String value) {
            addCriterion("DicID <>", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidGreaterThan(String value) {
            addCriterion("DicID >", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidGreaterThanOrEqualTo(String value) {
            addCriterion("DicID >=", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidLessThan(String value) {
            addCriterion("DicID <", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidLessThanOrEqualTo(String value) {
            addCriterion("DicID <=", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidLike(String value) {
            addCriterion("DicID like", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidNotLike(String value) {
            addCriterion("DicID not like", value, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidIn(List<String> values) {
            addCriterion("DicID in", values, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidNotIn(List<String> values) {
            addCriterion("DicID not in", values, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidBetween(String value1, String value2) {
            addCriterion("DicID between", value1, value2, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicidNotBetween(String value1, String value2) {
            addCriterion("DicID not between", value1, value2, "dicid");
            return (Criteria) this;
        }

        public Criteria andDicnameIsNull() {
            addCriterion("DicName is null");
            return (Criteria) this;
        }

        public Criteria andDicnameIsNotNull() {
            addCriterion("DicName is not null");
            return (Criteria) this;
        }

        public Criteria andDicnameEqualTo(String value) {
            addCriterion("DicName =", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameNotEqualTo(String value) {
            addCriterion("DicName <>", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameGreaterThan(String value) {
            addCriterion("DicName >", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameGreaterThanOrEqualTo(String value) {
            addCriterion("DicName >=", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameLessThan(String value) {
            addCriterion("DicName <", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameLessThanOrEqualTo(String value) {
            addCriterion("DicName <=", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameLike(String value) {
            addCriterion("DicName like", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameNotLike(String value) {
            addCriterion("DicName not like", value, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameIn(List<String> values) {
            addCriterion("DicName in", values, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameNotIn(List<String> values) {
            addCriterion("DicName not in", values, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameBetween(String value1, String value2) {
            addCriterion("DicName between", value1, value2, "dicname");
            return (Criteria) this;
        }

        public Criteria andDicnameNotBetween(String value1, String value2) {
            addCriterion("DicName not between", value1, value2, "dicname");
            return (Criteria) this;
        }

        public Criteria andSubtypeIsNull() {
            addCriterion("SubType is null");
            return (Criteria) this;
        }

        public Criteria andSubtypeIsNotNull() {
            addCriterion("SubType is not null");
            return (Criteria) this;
        }

        public Criteria andSubtypeEqualTo(String value) {
            addCriterion("SubType =", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotEqualTo(String value) {
            addCriterion("SubType <>", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeGreaterThan(String value) {
            addCriterion("SubType >", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeGreaterThanOrEqualTo(String value) {
            addCriterion("SubType >=", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeLessThan(String value) {
            addCriterion("SubType <", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeLessThanOrEqualTo(String value) {
            addCriterion("SubType <=", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeLike(String value) {
            addCriterion("SubType like", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotLike(String value) {
            addCriterion("SubType not like", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeIn(List<String> values) {
            addCriterion("SubType in", values, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotIn(List<String> values) {
            addCriterion("SubType not in", values, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeBetween(String value1, String value2) {
            addCriterion("SubType between", value1, value2, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotBetween(String value1, String value2) {
            addCriterion("SubType not between", value1, value2, "subtype");
            return (Criteria) this;
        }

        public Criteria andDictextIsNull() {
            addCriterion("DicText is null");
            return (Criteria) this;
        }

        public Criteria andDictextIsNotNull() {
            addCriterion("DicText is not null");
            return (Criteria) this;
        }

        public Criteria andDictextEqualTo(String value) {
            addCriterion("DicText =", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextNotEqualTo(String value) {
            addCriterion("DicText <>", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextGreaterThan(String value) {
            addCriterion("DicText >", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextGreaterThanOrEqualTo(String value) {
            addCriterion("DicText >=", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextLessThan(String value) {
            addCriterion("DicText <", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextLessThanOrEqualTo(String value) {
            addCriterion("DicText <=", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextLike(String value) {
            addCriterion("DicText like", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextNotLike(String value) {
            addCriterion("DicText not like", value, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextIn(List<String> values) {
            addCriterion("DicText in", values, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextNotIn(List<String> values) {
            addCriterion("DicText not in", values, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextBetween(String value1, String value2) {
            addCriterion("DicText between", value1, value2, "dictext");
            return (Criteria) this;
        }

        public Criteria andDictextNotBetween(String value1, String value2) {
            addCriterion("DicText not between", value1, value2, "dictext");
            return (Criteria) this;
        }

        public Criteria andDicorderIsNull() {
            addCriterion("DicOrder is null");
            return (Criteria) this;
        }

        public Criteria andDicorderIsNotNull() {
            addCriterion("DicOrder is not null");
            return (Criteria) this;
        }

        public Criteria andDicorderEqualTo(String value) {
            addCriterion("DicOrder =", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderNotEqualTo(String value) {
            addCriterion("DicOrder <>", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderGreaterThan(String value) {
            addCriterion("DicOrder >", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderGreaterThanOrEqualTo(String value) {
            addCriterion("DicOrder >=", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderLessThan(String value) {
            addCriterion("DicOrder <", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderLessThanOrEqualTo(String value) {
            addCriterion("DicOrder <=", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderLike(String value) {
            addCriterion("DicOrder like", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderNotLike(String value) {
            addCriterion("DicOrder not like", value, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderIn(List<String> values) {
            addCriterion("DicOrder in", values, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderNotIn(List<String> values) {
            addCriterion("DicOrder not in", values, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderBetween(String value1, String value2) {
            addCriterion("DicOrder between", value1, value2, "dicorder");
            return (Criteria) this;
        }

        public Criteria andDicorderNotBetween(String value1, String value2) {
            addCriterion("DicOrder not between", value1, value2, "dicorder");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("Status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("Status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andNamespellIsNull() {
            addCriterion("NameSpell is null");
            return (Criteria) this;
        }

        public Criteria andNamespellIsNotNull() {
            addCriterion("NameSpell is not null");
            return (Criteria) this;
        }

        public Criteria andNamespellEqualTo(String value) {
            addCriterion("NameSpell =", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellNotEqualTo(String value) {
            addCriterion("NameSpell <>", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellGreaterThan(String value) {
            addCriterion("NameSpell >", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellGreaterThanOrEqualTo(String value) {
            addCriterion("NameSpell >=", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellLessThan(String value) {
            addCriterion("NameSpell <", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellLessThanOrEqualTo(String value) {
            addCriterion("NameSpell <=", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellLike(String value) {
            addCriterion("NameSpell like", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellNotLike(String value) {
            addCriterion("NameSpell not like", value, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellIn(List<String> values) {
            addCriterion("NameSpell in", values, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellNotIn(List<String> values) {
            addCriterion("NameSpell not in", values, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellBetween(String value1, String value2) {
            addCriterion("NameSpell between", value1, value2, "namespell");
            return (Criteria) this;
        }

        public Criteria andNamespellNotBetween(String value1, String value2) {
            addCriterion("NameSpell not between", value1, value2, "namespell");
            return (Criteria) this;
        }

        public Criteria andInfoIsNull() {
            addCriterion("Info is null");
            return (Criteria) this;
        }

        public Criteria andInfoIsNotNull() {
            addCriterion("Info is not null");
            return (Criteria) this;
        }

        public Criteria andInfoEqualTo(String value) {
            addCriterion("Info =", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotEqualTo(String value) {
            addCriterion("Info <>", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThan(String value) {
            addCriterion("Info >", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoGreaterThanOrEqualTo(String value) {
            addCriterion("Info >=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThan(String value) {
            addCriterion("Info <", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLessThanOrEqualTo(String value) {
            addCriterion("Info <=", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoLike(String value) {
            addCriterion("Info like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotLike(String value) {
            addCriterion("Info not like", value, "info");
            return (Criteria) this;
        }

        public Criteria andInfoIn(List<String> values) {
            addCriterion("Info in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotIn(List<String> values) {
            addCriterion("Info not in", values, "info");
            return (Criteria) this;
        }

        public Criteria andInfoBetween(String value1, String value2) {
            addCriterion("Info between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andInfoNotBetween(String value1, String value2) {
            addCriterion("Info not between", value1, value2, "info");
            return (Criteria) this;
        }

        public Criteria andDicidLikeInsensitive(String value) {
            addCriterion("upper(DicID) like", value.toUpperCase(), "dicid");
            return (Criteria) this;
        }

        public Criteria andDicnameLikeInsensitive(String value) {
            addCriterion("upper(DicName) like", value.toUpperCase(), "dicname");
            return (Criteria) this;
        }

        public Criteria andSubtypeLikeInsensitive(String value) {
            addCriterion("upper(SubType) like", value.toUpperCase(), "subtype");
            return (Criteria) this;
        }

        public Criteria andDictextLikeInsensitive(String value) {
            addCriterion("upper(DicText) like", value.toUpperCase(), "dictext");
            return (Criteria) this;
        }

        public Criteria andDicorderLikeInsensitive(String value) {
            addCriterion("upper(DicOrder) like", value.toUpperCase(), "dicorder");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(Status) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andNamespellLikeInsensitive(String value) {
            addCriterion("upper(NameSpell) like", value.toUpperCase(), "namespell");
            return (Criteria) this;
        }

        public Criteria andInfoLikeInsensitive(String value) {
            addCriterion("upper(Info) like", value.toUpperCase(), "info");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm_dictionary
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}