package com.xiangshangkan.framtest.auto.entity;

import java.io.Serializable;

public class CmDictionaryEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.DicID
     *
     * @mbggenerated
     */
    private String dicid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.DicName
     *
     * @mbggenerated
     */
    private String dicname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.SubType
     *
     * @mbggenerated
     */
    private String subtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.DicText
     *
     * @mbggenerated
     */
    private String dictext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.DicOrder
     *
     * @mbggenerated
     */
    private String dicorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.NameSpell
     *
     * @mbggenerated
     */
    private String namespell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cm_dictionary.Info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.DicID
     *
     * @return the value of cm_dictionary.DicID
     *
     * @mbggenerated
     */
    public String getDicid() {
        return dicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.DicID
     *
     * @param dicid the value for cm_dictionary.DicID
     *
     * @mbggenerated
     */
    public void setDicid(String dicid) {
        this.dicid = dicid == null ? null : dicid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.DicName
     *
     * @return the value of cm_dictionary.DicName
     *
     * @mbggenerated
     */
    public String getDicname() {
        return dicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.DicName
     *
     * @param dicname the value for cm_dictionary.DicName
     *
     * @mbggenerated
     */
    public void setDicname(String dicname) {
        this.dicname = dicname == null ? null : dicname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.SubType
     *
     * @return the value of cm_dictionary.SubType
     *
     * @mbggenerated
     */
    public String getSubtype() {
        return subtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.SubType
     *
     * @param subtype the value for cm_dictionary.SubType
     *
     * @mbggenerated
     */
    public void setSubtype(String subtype) {
        this.subtype = subtype == null ? null : subtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.DicText
     *
     * @return the value of cm_dictionary.DicText
     *
     * @mbggenerated
     */
    public String getDictext() {
        return dictext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.DicText
     *
     * @param dictext the value for cm_dictionary.DicText
     *
     * @mbggenerated
     */
    public void setDictext(String dictext) {
        this.dictext = dictext == null ? null : dictext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.DicOrder
     *
     * @return the value of cm_dictionary.DicOrder
     *
     * @mbggenerated
     */
    public String getDicorder() {
        return dicorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.DicOrder
     *
     * @param dicorder the value for cm_dictionary.DicOrder
     *
     * @mbggenerated
     */
    public void setDicorder(String dicorder) {
        this.dicorder = dicorder == null ? null : dicorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.Status
     *
     * @return the value of cm_dictionary.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.Status
     *
     * @param status the value for cm_dictionary.Status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.NameSpell
     *
     * @return the value of cm_dictionary.NameSpell
     *
     * @mbggenerated
     */
    public String getNamespell() {
        return namespell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.NameSpell
     *
     * @param namespell the value for cm_dictionary.NameSpell
     *
     * @mbggenerated
     */
    public void setNamespell(String namespell) {
        this.namespell = namespell == null ? null : namespell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cm_dictionary.Info
     *
     * @return the value of cm_dictionary.Info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cm_dictionary.Info
     *
     * @param info the value for cm_dictionary.Info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dicid=").append(dicid);
        sb.append(", dicname=").append(dicname);
        sb.append(", subtype=").append(subtype);
        sb.append(", dictext=").append(dictext);
        sb.append(", dicorder=").append(dicorder);
        sb.append(", status=").append(status);
        sb.append(", namespell=").append(namespell);
        sb.append(", info=").append(info);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CmDictionaryEntity other = (CmDictionaryEntity) that;
        return (this.getDicid() == null ? other.getDicid() == null : this.getDicid().equals(other.getDicid()))
            && (this.getDicname() == null ? other.getDicname() == null : this.getDicname().equals(other.getDicname()))
            && (this.getSubtype() == null ? other.getSubtype() == null : this.getSubtype().equals(other.getSubtype()))
            && (this.getDictext() == null ? other.getDictext() == null : this.getDictext().equals(other.getDictext()))
            && (this.getDicorder() == null ? other.getDicorder() == null : this.getDicorder().equals(other.getDicorder()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getNamespell() == null ? other.getNamespell() == null : this.getNamespell().equals(other.getNamespell()))
            && (this.getInfo() == null ? other.getInfo() == null : this.getInfo().equals(other.getInfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cm_dictionary
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDicid() == null) ? 0 : getDicid().hashCode());
        result = prime * result + ((getDicname() == null) ? 0 : getDicname().hashCode());
        result = prime * result + ((getSubtype() == null) ? 0 : getSubtype().hashCode());
        result = prime * result + ((getDictext() == null) ? 0 : getDictext().hashCode());
        result = prime * result + ((getDicorder() == null) ? 0 : getDicorder().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getNamespell() == null) ? 0 : getNamespell().hashCode());
        result = prime * result + ((getInfo() == null) ? 0 : getInfo().hashCode());
        return result;
    }
}