package com.xiangshangkan.framtest.auto.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class LicenseBusinessInfoEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.base_id
     *
     * @mbggenerated
     */
    private Integer baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.company_address
     *
     * @mbggenerated
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.license_number
     *
     * @mbggenerated
     */
    private String licenseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.principal
     *
     * @mbggenerated
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.principal_number
     *
     * @mbggenerated
     */
    private String principalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.legal
     *
     * @mbggenerated
     */
    private String legal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.legal_number
     *
     * @mbggenerated
     */
    private String legalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.establishment_date
     *
     * @mbggenerated
     */
    private Date establishmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.expiry_date
     *
     * @mbggenerated
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.annual_inspection_type
     *
     * @mbggenerated
     */
    private Integer annualInspectionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.annual_start_month
     *
     * @mbggenerated
     */
    private Integer annualStartMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.annual_end_month
     *
     * @mbggenerated
     */
    private Integer annualEndMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.annual_inspection_date
     *
     * @mbggenerated
     */
    private Date annualInspectionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.custodian_number
     *
     * @mbggenerated
     */
    private String custodianNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.custodian
     *
     * @mbggenerated
     */
    private String custodian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.custodian_dept_number
     *
     * @mbggenerated
     */
    private String custodianDeptNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.custodian_dept
     *
     * @mbggenerated
     */
    private String custodianDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.executive_director
     *
     * @mbggenerated
     */
    private String executiveDirector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.executive_director_number
     *
     * @mbggenerated
     */
    private String executiveDirectorNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.general_manager
     *
     * @mbggenerated
     */
    private String generalManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.general_manager_number
     *
     * @mbggenerated
     */
    private String generalManagerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.supervisor
     *
     * @mbggenerated
     */
    private String supervisor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.supervisor_number
     *
     * @mbggenerated
     */
    private String supervisorNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.annual_inspection_month
     *
     * @mbggenerated
     */
    private Integer annualInspectionMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.registered_capital
     *
     * @mbggenerated
     */
    private BigDecimal registeredCapital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.paid_in_amount
     *
     * @mbggenerated
     */
    private BigDecimal paidInAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.expiry_date_type
     *
     * @mbggenerated
     */
    private Integer expiryDateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.province_id
     *
     * @mbggenerated
     */
    private String provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.city_id
     *
     * @mbggenerated
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.city_area
     *
     * @mbggenerated
     */
    private String cityArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.store_serial
     *
     * @mbggenerated
     */
    private String storeSerial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column license_business_info.serial
     *
     * @mbggenerated
     */
    private Integer serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.id
     *
     * @return the value of license_business_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.id
     *
     * @param id the value for license_business_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.base_id
     *
     * @return the value of license_business_info.base_id
     *
     * @mbggenerated
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.base_id
     *
     * @param baseId the value for license_business_info.base_id
     *
     * @mbggenerated
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.company
     *
     * @return the value of license_business_info.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.company
     *
     * @param company the value for license_business_info.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.company_address
     *
     * @return the value of license_business_info.company_address
     *
     * @mbggenerated
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.company_address
     *
     * @param companyAddress the value for license_business_info.company_address
     *
     * @mbggenerated
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.license_number
     *
     * @return the value of license_business_info.license_number
     *
     * @mbggenerated
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.license_number
     *
     * @param licenseNumber the value for license_business_info.license_number
     *
     * @mbggenerated
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber == null ? null : licenseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.principal
     *
     * @return the value of license_business_info.principal
     *
     * @mbggenerated
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.principal
     *
     * @param principal the value for license_business_info.principal
     *
     * @mbggenerated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.principal_number
     *
     * @return the value of license_business_info.principal_number
     *
     * @mbggenerated
     */
    public String getPrincipalNumber() {
        return principalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.principal_number
     *
     * @param principalNumber the value for license_business_info.principal_number
     *
     * @mbggenerated
     */
    public void setPrincipalNumber(String principalNumber) {
        this.principalNumber = principalNumber == null ? null : principalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.legal
     *
     * @return the value of license_business_info.legal
     *
     * @mbggenerated
     */
    public String getLegal() {
        return legal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.legal
     *
     * @param legal the value for license_business_info.legal
     *
     * @mbggenerated
     */
    public void setLegal(String legal) {
        this.legal = legal == null ? null : legal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.legal_number
     *
     * @return the value of license_business_info.legal_number
     *
     * @mbggenerated
     */
    public String getLegalNumber() {
        return legalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.legal_number
     *
     * @param legalNumber the value for license_business_info.legal_number
     *
     * @mbggenerated
     */
    public void setLegalNumber(String legalNumber) {
        this.legalNumber = legalNumber == null ? null : legalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.establishment_date
     *
     * @return the value of license_business_info.establishment_date
     *
     * @mbggenerated
     */
    public Date getEstablishmentDate() {
        return establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.establishment_date
     *
     * @param establishmentDate the value for license_business_info.establishment_date
     *
     * @mbggenerated
     */
    public void setEstablishmentDate(Date establishmentDate) {
        this.establishmentDate = establishmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.expiry_date
     *
     * @return the value of license_business_info.expiry_date
     *
     * @mbggenerated
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.expiry_date
     *
     * @param expiryDate the value for license_business_info.expiry_date
     *
     * @mbggenerated
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.annual_inspection_type
     *
     * @return the value of license_business_info.annual_inspection_type
     *
     * @mbggenerated
     */
    public Integer getAnnualInspectionType() {
        return annualInspectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.annual_inspection_type
     *
     * @param annualInspectionType the value for license_business_info.annual_inspection_type
     *
     * @mbggenerated
     */
    public void setAnnualInspectionType(Integer annualInspectionType) {
        this.annualInspectionType = annualInspectionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.annual_start_month
     *
     * @return the value of license_business_info.annual_start_month
     *
     * @mbggenerated
     */
    public Integer getAnnualStartMonth() {
        return annualStartMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.annual_start_month
     *
     * @param annualStartMonth the value for license_business_info.annual_start_month
     *
     * @mbggenerated
     */
    public void setAnnualStartMonth(Integer annualStartMonth) {
        this.annualStartMonth = annualStartMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.annual_end_month
     *
     * @return the value of license_business_info.annual_end_month
     *
     * @mbggenerated
     */
    public Integer getAnnualEndMonth() {
        return annualEndMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.annual_end_month
     *
     * @param annualEndMonth the value for license_business_info.annual_end_month
     *
     * @mbggenerated
     */
    public void setAnnualEndMonth(Integer annualEndMonth) {
        this.annualEndMonth = annualEndMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.annual_inspection_date
     *
     * @return the value of license_business_info.annual_inspection_date
     *
     * @mbggenerated
     */
    public Date getAnnualInspectionDate() {
        return annualInspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.annual_inspection_date
     *
     * @param annualInspectionDate the value for license_business_info.annual_inspection_date
     *
     * @mbggenerated
     */
    public void setAnnualInspectionDate(Date annualInspectionDate) {
        this.annualInspectionDate = annualInspectionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.custodian_number
     *
     * @return the value of license_business_info.custodian_number
     *
     * @mbggenerated
     */
    public String getCustodianNumber() {
        return custodianNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.custodian_number
     *
     * @param custodianNumber the value for license_business_info.custodian_number
     *
     * @mbggenerated
     */
    public void setCustodianNumber(String custodianNumber) {
        this.custodianNumber = custodianNumber == null ? null : custodianNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.custodian
     *
     * @return the value of license_business_info.custodian
     *
     * @mbggenerated
     */
    public String getCustodian() {
        return custodian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.custodian
     *
     * @param custodian the value for license_business_info.custodian
     *
     * @mbggenerated
     */
    public void setCustodian(String custodian) {
        this.custodian = custodian == null ? null : custodian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.custodian_dept_number
     *
     * @return the value of license_business_info.custodian_dept_number
     *
     * @mbggenerated
     */
    public String getCustodianDeptNumber() {
        return custodianDeptNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.custodian_dept_number
     *
     * @param custodianDeptNumber the value for license_business_info.custodian_dept_number
     *
     * @mbggenerated
     */
    public void setCustodianDeptNumber(String custodianDeptNumber) {
        this.custodianDeptNumber = custodianDeptNumber == null ? null : custodianDeptNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.custodian_dept
     *
     * @return the value of license_business_info.custodian_dept
     *
     * @mbggenerated
     */
    public String getCustodianDept() {
        return custodianDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.custodian_dept
     *
     * @param custodianDept the value for license_business_info.custodian_dept
     *
     * @mbggenerated
     */
    public void setCustodianDept(String custodianDept) {
        this.custodianDept = custodianDept == null ? null : custodianDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.executive_director
     *
     * @return the value of license_business_info.executive_director
     *
     * @mbggenerated
     */
    public String getExecutiveDirector() {
        return executiveDirector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.executive_director
     *
     * @param executiveDirector the value for license_business_info.executive_director
     *
     * @mbggenerated
     */
    public void setExecutiveDirector(String executiveDirector) {
        this.executiveDirector = executiveDirector == null ? null : executiveDirector.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.executive_director_number
     *
     * @return the value of license_business_info.executive_director_number
     *
     * @mbggenerated
     */
    public String getExecutiveDirectorNumber() {
        return executiveDirectorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.executive_director_number
     *
     * @param executiveDirectorNumber the value for license_business_info.executive_director_number
     *
     * @mbggenerated
     */
    public void setExecutiveDirectorNumber(String executiveDirectorNumber) {
        this.executiveDirectorNumber = executiveDirectorNumber == null ? null : executiveDirectorNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.general_manager
     *
     * @return the value of license_business_info.general_manager
     *
     * @mbggenerated
     */
    public String getGeneralManager() {
        return generalManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.general_manager
     *
     * @param generalManager the value for license_business_info.general_manager
     *
     * @mbggenerated
     */
    public void setGeneralManager(String generalManager) {
        this.generalManager = generalManager == null ? null : generalManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.general_manager_number
     *
     * @return the value of license_business_info.general_manager_number
     *
     * @mbggenerated
     */
    public String getGeneralManagerNumber() {
        return generalManagerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.general_manager_number
     *
     * @param generalManagerNumber the value for license_business_info.general_manager_number
     *
     * @mbggenerated
     */
    public void setGeneralManagerNumber(String generalManagerNumber) {
        this.generalManagerNumber = generalManagerNumber == null ? null : generalManagerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.supervisor
     *
     * @return the value of license_business_info.supervisor
     *
     * @mbggenerated
     */
    public String getSupervisor() {
        return supervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.supervisor
     *
     * @param supervisor the value for license_business_info.supervisor
     *
     * @mbggenerated
     */
    public void setSupervisor(String supervisor) {
        this.supervisor = supervisor == null ? null : supervisor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.supervisor_number
     *
     * @return the value of license_business_info.supervisor_number
     *
     * @mbggenerated
     */
    public String getSupervisorNumber() {
        return supervisorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.supervisor_number
     *
     * @param supervisorNumber the value for license_business_info.supervisor_number
     *
     * @mbggenerated
     */
    public void setSupervisorNumber(String supervisorNumber) {
        this.supervisorNumber = supervisorNumber == null ? null : supervisorNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.create_time
     *
     * @return the value of license_business_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.create_time
     *
     * @param createTime the value for license_business_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.update_time
     *
     * @return the value of license_business_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.update_time
     *
     * @param updateTime the value for license_business_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.annual_inspection_month
     *
     * @return the value of license_business_info.annual_inspection_month
     *
     * @mbggenerated
     */
    public Integer getAnnualInspectionMonth() {
        return annualInspectionMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.annual_inspection_month
     *
     * @param annualInspectionMonth the value for license_business_info.annual_inspection_month
     *
     * @mbggenerated
     */
    public void setAnnualInspectionMonth(Integer annualInspectionMonth) {
        this.annualInspectionMonth = annualInspectionMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.registered_capital
     *
     * @return the value of license_business_info.registered_capital
     *
     * @mbggenerated
     */
    public BigDecimal getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.registered_capital
     *
     * @param registeredCapital the value for license_business_info.registered_capital
     *
     * @mbggenerated
     */
    public void setRegisteredCapital(BigDecimal registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.paid_in_amount
     *
     * @return the value of license_business_info.paid_in_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPaidInAmount() {
        return paidInAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.paid_in_amount
     *
     * @param paidInAmount the value for license_business_info.paid_in_amount
     *
     * @mbggenerated
     */
    public void setPaidInAmount(BigDecimal paidInAmount) {
        this.paidInAmount = paidInAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.expiry_date_type
     *
     * @return the value of license_business_info.expiry_date_type
     *
     * @mbggenerated
     */
    public Integer getExpiryDateType() {
        return expiryDateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.expiry_date_type
     *
     * @param expiryDateType the value for license_business_info.expiry_date_type
     *
     * @mbggenerated
     */
    public void setExpiryDateType(Integer expiryDateType) {
        this.expiryDateType = expiryDateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.province_id
     *
     * @return the value of license_business_info.province_id
     *
     * @mbggenerated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.province_id
     *
     * @param provinceId the value for license_business_info.province_id
     *
     * @mbggenerated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId == null ? null : provinceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.city_id
     *
     * @return the value of license_business_info.city_id
     *
     * @mbggenerated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.city_id
     *
     * @param cityId the value for license_business_info.city_id
     *
     * @mbggenerated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.city_area
     *
     * @return the value of license_business_info.city_area
     *
     * @mbggenerated
     */
    public String getCityArea() {
        return cityArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.city_area
     *
     * @param cityArea the value for license_business_info.city_area
     *
     * @mbggenerated
     */
    public void setCityArea(String cityArea) {
        this.cityArea = cityArea == null ? null : cityArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.addr
     *
     * @return the value of license_business_info.addr
     *
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.addr
     *
     * @param addr the value for license_business_info.addr
     *
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.store_serial
     *
     * @return the value of license_business_info.store_serial
     *
     * @mbggenerated
     */
    public String getStoreSerial() {
        return storeSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.store_serial
     *
     * @param storeSerial the value for license_business_info.store_serial
     *
     * @mbggenerated
     */
    public void setStoreSerial(String storeSerial) {
        this.storeSerial = storeSerial == null ? null : storeSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column license_business_info.serial
     *
     * @return the value of license_business_info.serial
     *
     * @mbggenerated
     */
    public Integer getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column license_business_info.serial
     *
     * @param serial the value for license_business_info.serial
     *
     * @mbggenerated
     */
    public void setSerial(Integer serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", baseId=").append(baseId);
        sb.append(", company=").append(company);
        sb.append(", companyAddress=").append(companyAddress);
        sb.append(", licenseNumber=").append(licenseNumber);
        sb.append(", principal=").append(principal);
        sb.append(", principalNumber=").append(principalNumber);
        sb.append(", legal=").append(legal);
        sb.append(", legalNumber=").append(legalNumber);
        sb.append(", establishmentDate=").append(establishmentDate);
        sb.append(", expiryDate=").append(expiryDate);
        sb.append(", annualInspectionType=").append(annualInspectionType);
        sb.append(", annualStartMonth=").append(annualStartMonth);
        sb.append(", annualEndMonth=").append(annualEndMonth);
        sb.append(", annualInspectionDate=").append(annualInspectionDate);
        sb.append(", custodianNumber=").append(custodianNumber);
        sb.append(", custodian=").append(custodian);
        sb.append(", custodianDeptNumber=").append(custodianDeptNumber);
        sb.append(", custodianDept=").append(custodianDept);
        sb.append(", executiveDirector=").append(executiveDirector);
        sb.append(", executiveDirectorNumber=").append(executiveDirectorNumber);
        sb.append(", generalManager=").append(generalManager);
        sb.append(", generalManagerNumber=").append(generalManagerNumber);
        sb.append(", supervisor=").append(supervisor);
        sb.append(", supervisorNumber=").append(supervisorNumber);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", annualInspectionMonth=").append(annualInspectionMonth);
        sb.append(", registeredCapital=").append(registeredCapital);
        sb.append(", paidInAmount=").append(paidInAmount);
        sb.append(", expiryDateType=").append(expiryDateType);
        sb.append(", provinceId=").append(provinceId);
        sb.append(", cityId=").append(cityId);
        sb.append(", cityArea=").append(cityArea);
        sb.append(", addr=").append(addr);
        sb.append(", storeSerial=").append(storeSerial);
        sb.append(", serial=").append(serial);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LicenseBusinessInfoEntity other = (LicenseBusinessInfoEntity) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBaseId() == null ? other.getBaseId() == null : this.getBaseId().equals(other.getBaseId()))
            && (this.getCompany() == null ? other.getCompany() == null : this.getCompany().equals(other.getCompany()))
            && (this.getCompanyAddress() == null ? other.getCompanyAddress() == null : this.getCompanyAddress().equals(other.getCompanyAddress()))
            && (this.getLicenseNumber() == null ? other.getLicenseNumber() == null : this.getLicenseNumber().equals(other.getLicenseNumber()))
            && (this.getPrincipal() == null ? other.getPrincipal() == null : this.getPrincipal().equals(other.getPrincipal()))
            && (this.getPrincipalNumber() == null ? other.getPrincipalNumber() == null : this.getPrincipalNumber().equals(other.getPrincipalNumber()))
            && (this.getLegal() == null ? other.getLegal() == null : this.getLegal().equals(other.getLegal()))
            && (this.getLegalNumber() == null ? other.getLegalNumber() == null : this.getLegalNumber().equals(other.getLegalNumber()))
            && (this.getEstablishmentDate() == null ? other.getEstablishmentDate() == null : this.getEstablishmentDate().equals(other.getEstablishmentDate()))
            && (this.getExpiryDate() == null ? other.getExpiryDate() == null : this.getExpiryDate().equals(other.getExpiryDate()))
            && (this.getAnnualInspectionType() == null ? other.getAnnualInspectionType() == null : this.getAnnualInspectionType().equals(other.getAnnualInspectionType()))
            && (this.getAnnualStartMonth() == null ? other.getAnnualStartMonth() == null : this.getAnnualStartMonth().equals(other.getAnnualStartMonth()))
            && (this.getAnnualEndMonth() == null ? other.getAnnualEndMonth() == null : this.getAnnualEndMonth().equals(other.getAnnualEndMonth()))
            && (this.getAnnualInspectionDate() == null ? other.getAnnualInspectionDate() == null : this.getAnnualInspectionDate().equals(other.getAnnualInspectionDate()))
            && (this.getCustodianNumber() == null ? other.getCustodianNumber() == null : this.getCustodianNumber().equals(other.getCustodianNumber()))
            && (this.getCustodian() == null ? other.getCustodian() == null : this.getCustodian().equals(other.getCustodian()))
            && (this.getCustodianDeptNumber() == null ? other.getCustodianDeptNumber() == null : this.getCustodianDeptNumber().equals(other.getCustodianDeptNumber()))
            && (this.getCustodianDept() == null ? other.getCustodianDept() == null : this.getCustodianDept().equals(other.getCustodianDept()))
            && (this.getExecutiveDirector() == null ? other.getExecutiveDirector() == null : this.getExecutiveDirector().equals(other.getExecutiveDirector()))
            && (this.getExecutiveDirectorNumber() == null ? other.getExecutiveDirectorNumber() == null : this.getExecutiveDirectorNumber().equals(other.getExecutiveDirectorNumber()))
            && (this.getGeneralManager() == null ? other.getGeneralManager() == null : this.getGeneralManager().equals(other.getGeneralManager()))
            && (this.getGeneralManagerNumber() == null ? other.getGeneralManagerNumber() == null : this.getGeneralManagerNumber().equals(other.getGeneralManagerNumber()))
            && (this.getSupervisor() == null ? other.getSupervisor() == null : this.getSupervisor().equals(other.getSupervisor()))
            && (this.getSupervisorNumber() == null ? other.getSupervisorNumber() == null : this.getSupervisorNumber().equals(other.getSupervisorNumber()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getAnnualInspectionMonth() == null ? other.getAnnualInspectionMonth() == null : this.getAnnualInspectionMonth().equals(other.getAnnualInspectionMonth()))
            && (this.getRegisteredCapital() == null ? other.getRegisteredCapital() == null : this.getRegisteredCapital().equals(other.getRegisteredCapital()))
            && (this.getPaidInAmount() == null ? other.getPaidInAmount() == null : this.getPaidInAmount().equals(other.getPaidInAmount()))
            && (this.getExpiryDateType() == null ? other.getExpiryDateType() == null : this.getExpiryDateType().equals(other.getExpiryDateType()))
            && (this.getProvinceId() == null ? other.getProvinceId() == null : this.getProvinceId().equals(other.getProvinceId()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getCityArea() == null ? other.getCityArea() == null : this.getCityArea().equals(other.getCityArea()))
            && (this.getAddr() == null ? other.getAddr() == null : this.getAddr().equals(other.getAddr()))
            && (this.getStoreSerial() == null ? other.getStoreSerial() == null : this.getStoreSerial().equals(other.getStoreSerial()))
            && (this.getSerial() == null ? other.getSerial() == null : this.getSerial().equals(other.getSerial()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table license_business_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBaseId() == null) ? 0 : getBaseId().hashCode());
        result = prime * result + ((getCompany() == null) ? 0 : getCompany().hashCode());
        result = prime * result + ((getCompanyAddress() == null) ? 0 : getCompanyAddress().hashCode());
        result = prime * result + ((getLicenseNumber() == null) ? 0 : getLicenseNumber().hashCode());
        result = prime * result + ((getPrincipal() == null) ? 0 : getPrincipal().hashCode());
        result = prime * result + ((getPrincipalNumber() == null) ? 0 : getPrincipalNumber().hashCode());
        result = prime * result + ((getLegal() == null) ? 0 : getLegal().hashCode());
        result = prime * result + ((getLegalNumber() == null) ? 0 : getLegalNumber().hashCode());
        result = prime * result + ((getEstablishmentDate() == null) ? 0 : getEstablishmentDate().hashCode());
        result = prime * result + ((getExpiryDate() == null) ? 0 : getExpiryDate().hashCode());
        result = prime * result + ((getAnnualInspectionType() == null) ? 0 : getAnnualInspectionType().hashCode());
        result = prime * result + ((getAnnualStartMonth() == null) ? 0 : getAnnualStartMonth().hashCode());
        result = prime * result + ((getAnnualEndMonth() == null) ? 0 : getAnnualEndMonth().hashCode());
        result = prime * result + ((getAnnualInspectionDate() == null) ? 0 : getAnnualInspectionDate().hashCode());
        result = prime * result + ((getCustodianNumber() == null) ? 0 : getCustodianNumber().hashCode());
        result = prime * result + ((getCustodian() == null) ? 0 : getCustodian().hashCode());
        result = prime * result + ((getCustodianDeptNumber() == null) ? 0 : getCustodianDeptNumber().hashCode());
        result = prime * result + ((getCustodianDept() == null) ? 0 : getCustodianDept().hashCode());
        result = prime * result + ((getExecutiveDirector() == null) ? 0 : getExecutiveDirector().hashCode());
        result = prime * result + ((getExecutiveDirectorNumber() == null) ? 0 : getExecutiveDirectorNumber().hashCode());
        result = prime * result + ((getGeneralManager() == null) ? 0 : getGeneralManager().hashCode());
        result = prime * result + ((getGeneralManagerNumber() == null) ? 0 : getGeneralManagerNumber().hashCode());
        result = prime * result + ((getSupervisor() == null) ? 0 : getSupervisor().hashCode());
        result = prime * result + ((getSupervisorNumber() == null) ? 0 : getSupervisorNumber().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getAnnualInspectionMonth() == null) ? 0 : getAnnualInspectionMonth().hashCode());
        result = prime * result + ((getRegisteredCapital() == null) ? 0 : getRegisteredCapital().hashCode());
        result = prime * result + ((getPaidInAmount() == null) ? 0 : getPaidInAmount().hashCode());
        result = prime * result + ((getExpiryDateType() == null) ? 0 : getExpiryDateType().hashCode());
        result = prime * result + ((getProvinceId() == null) ? 0 : getProvinceId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getCityArea() == null) ? 0 : getCityArea().hashCode());
        result = prime * result + ((getAddr() == null) ? 0 : getAddr().hashCode());
        result = prime * result + ((getStoreSerial() == null) ? 0 : getStoreSerial().hashCode());
        result = prime * result + ((getSerial() == null) ? 0 : getSerial().hashCode());
        return result;
    }
}